# Etapa de construção
FROM node:16-alpine as build
WORKDIR /app

# Instalar dependências do sistema necessárias para npm
RUN apk add --no-cache python3 make g++

# Copiar package.json e package-lock.json
COPY frontend/react-auth/package*.json ./

# Instalar dependências com a flag legacy-peer-deps
RUN npm ci --legacy-peer-deps --verbose

# Copiar o resto dos arquivos do projeto
COPY frontend/react-auth/ ./

# Construir o aplicativo para produção
RUN npm run build

# Etapa de produção, usando Nginx para servir o conteúdo estático
FROM nginx:alpine

# Copiar os arquivos estáticos construídos
COPY --from=build /app/build /usr/share/nginx/html

# Copiar a configuração correta do Nginx
COPY frontend/react-auth/nginx.conf /etc/nginx/conf.d/default.conf

# Copiar o script de entrada personalizado
COPY frontend/react-auth/docker-entrypoint.sh /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh

# Copiar o novo script de configuração
COPY frontend/react-auth/config-overrides.sh /usr/share/nginx/html/config-overrides.sh
RUN chmod +x /usr/share/nginx/html/config-overrides.sh

# Expor a porta 80 para o Nginx
EXPOSE 80

# Usar o script de entrada personalizado para substituir variáveis e iniciar o Nginx
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["nginx", "-g", "daemon off;"]
