apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:                   # Adicione esta seção
    app: mysql               # Adicione este rótulo para que o serviço encontre o pod
spec:
  containers:
  - name: mysql
    image: mysql:5.7
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysql-secret
          key: mysql-root-password
    volumeMounts:
    - mountPath: "/var/lib/mysql"
      name: mysql-storage
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
      requests:
        memory: "256Mi"
        cpu: "250m"
  volumes:
  - name: mysql-storage
    persistentVolumeClaim:
      claimName: mysql-pvc
