server {
    listen 80;
    server_name _;

    # Diretório raiz onde os arquivos estáticos do React são servidos
    root /usr/share/nginx/html;
    index index.html;

    # Rotas do React
    location / {
        try_files $uri /index.html;  # Redireciona todas as rotas não encontradas para index.html
    }

    # Rota para arquivos estáticos
    location /static/ {
        add_header Cache-Control "public, max-age=31536000";
    }

    # Substituir as variáveis no runtime
    location /config.js {
        default_type "application/javascript";
        return 200 'window._env_ = {
            REACT_APP_API_URL: "$REACT_APP_API_URL"
        }';
    }

    # Páginas de erro
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
