# Nome do arquivo: nginx.conf

server {
    listen 80;
    server_name localhost;

    # Diretório raiz onde os arquivos estáticos do React são servidos
    root /usr/share/nginx/html;

    # Definir o comportamento padrão
    index index.html;

    # Local para servir arquivos estáticos
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Cache estático para otimizar o desempenho
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|otf|eot)$ {
        expires 1y;
        log_not_found off;
    }

    # Logs de erro
    error_log /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;
}
